---
# tasks file for Slave

- name: "Copying Hadoop RPM file"
  copy:
     dest: "/root/"
     src: "/root/hadoop-1.2.1-1.x86_64.rpm"

- name: "Copying JDK RPM file"
  copy:
     dest: "/root/"
     src: "/root/jdk-8u171-linux-x64.rpm"

- name: "Installing JDK"
  command:
     cmd: "rpm -i /root/jdk-8u171-linux-x64.rpm"
     creates: "/usr/bin/java"

- name: "Installing hadoop"
  command:
     cmd: "rpm -i /root/hadoop-1.2.1-1.x86_64.rpm --force"
     creates: "/usr/bin/hadoop"

- name: "Stopping Datanode"
  command:
     cmd: "hadoop-daemon.sh stop namenode"

- name: "Deleting Datanode directory"
  file:
     state: absent
     path: "{{ slave_dir }}"

- name: "Creating Datanode directory"
  file:
     state: directory
     path: "{{ slave_dir }}"

- name: "Configuring Slave's hdfs file"
  template:
     dest: "/etc/hadoop/hdfs-site.xml"
     src: "slave-hdfs.conf"

- name: "Configuring Slave's Core file"
  template:
     dest: "/etc/hadoop/core-site.xml"
     src: "slave-core.conf"

- name: "Starting Datanode"
  command:
     cmd: "hadoop-daemon.sh start datanode"
                                                 
